# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:p4PWfsS0u2dSUFQXpOc=,iv:lhKOuCqoKB8Vs2Ptkapz2o9xWSb7n4uGbkegy1ecoqo=,tag:gRP0gf0TJ58aFATp06BuDg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:gWSROey3amp2nMp0vBhJ01Ud,iv:EyK6G2I06eC69Omw1ju4i/NOtILuCihJKxYUggBxtrU=,tag:hAJFGUR1ZNykTquCCzd3iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-08T04:02:20Z"
    mac: ENC[AES256_GCM,data:EFKWY5Etv5dkNSZ3Dpqezv2Zcah+IvOKcl1ziq339HiapNo1Q/WHveQh4vPsRH5sjItUeHbTuabBLAP68UYy/XJWHP1xZx5+4628gicOtuda7b5SdwVS5++TR5NvKCZoeYhXuPlxDRvgOdLNGEdKvDkqOHqkIDLjusvesV8hZPc=,iv:TmYJxuEpuvyV/5uGP/LC3ILsYVQnpzNfZ+YDwXI0ZvE=,tag:/NE+Pvgm8i1Q2KAF6vuzNg==,type:str]
    pgp:
        - created_at: "2021-09-08T04:02:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4gzIuqEmpK/AQ/+M1kXkgWEwjAddm5jgXAvpWpJMI7vHzBLygpoCMcRPAXa
            AtBRV1Ggo71bxc39LDxOHUCNOgvDqrVyQrk7yJDlo68MdGekV4wn/4T/W4pOTCqr
            mJ9NT/oLTp3rNYJCcRcaXQD6iy9xaM1apOQBsLgljpaU2Q8uimJiSsn9Lek39kZA
            C5pm+iDpn70u1p9XjSheFtStxI2PrqtgyxN/dXKidN3jSihxGz/2Le1zj0rim3Oa
            So4n6l1mSWBDA5kyA2TKrd0CSeQb5DBzm2yXifFxrKG/vPl0AOdsGlgcBD19dUl/
            9l5PKECBRGceNdcsIaH5s9jJK+67Csjtdd2DpjedlbGMWMWm7or4gh7gis2B76yK
            bLiNziZkauQoYKNEKh6FdfMWssa7Pz/MVVa+s5foRrnagpNxySK9XhjKNKL74iBc
            dbGxcbndHYfGPsYxkfgP/QrgtnQOR5lvIQECIARUDYocxMODyERgIlvs+nWsHnru
            l0off6nwlLjvo0cJS2iecdiGx9JGN/cXOkGSZF0YJFvSFh8Cta/p62NpjL/sHZS8
            fdwUskYyiYnwo7ZPPDqYS6BDqq9fhp5jZXHgMATlkeTvurNBPWJCtQDg5WNg1yvj
            dI0Nj3FU/Wjvjtr8Z91EbcxNa/f6nGfnv5V+9vGGhi6j6/LZepNNj4klTxZWZyXS
            XgHPXTGyWBwrZtb5P9NU0vBX+vsSFwNsCVPiORjiRz3l1IUFBKTdcvK796hhrHO1
            NXCV9ErCGEncJr95AcsVnfialn0M5B0nMM28zs102UsqREhq5mnf+z0fRQ42l9E=
            =Kfpv
            -----END PGP MESSAGE-----
          fp: DEAD17F94A4CBA3331BD2542F2FB94B62CC9EE0E
        - created_at: "2021-09-08T04:02:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/3Zqf7p544gAQ//U537f2H+x5YIU4cDlfPk0EJgGsNw5jQ9N0ktsSzxJZtq
            nMt64/lV0tKX9vnfcwnEs6Od3vxwjVXx5pFKg33O9R7CcV8/YVL90VUOLny1nRXi
            ezyGZtAqWD86MJk9zAGYjgfx7M1M5sOnyW87OXDqFoLC1FPQnzjfs72tC/2r46bX
            QAoQbPtgzXBXK/lqTJ1P+hXEQ3qcsY6A2gGgCtP4fla9p5DBdfXBcpnhGvZ5dvR2
            OylKTe7dIR+40+uDjUNKa08BYwK8G0F3sbgDhq4e9GKZoMDPU4OrZgiGuaAtHg/Q
            KuavvsSmG4mRKm9VeZTT2Z0U8HrKy/zkqedvQUoghpcTU9W9f/YSeXWtBoaqlywZ
            7NAkX5RaUe5qH+YSHiXKAlPL9aU56cdocUEjizcbdMSD7EA1iUm26hYp3Kx8S1Cu
            PmxlYz8e1hY41IT0sPjirAz0o2knu//uHarxKzinoFa5O1J1uvMz8CeEvJJMnx8k
            KRLTzpHHa6u3cbnsg7q1kKz2LiE8u1V4xfTNZQRolL2EF0yjV5b5OS87UE0TYkbA
            0lPUcopXFPhQ42nqrz1McPP7TQFMmPov3P3UG3psHxuqpK/bTmMbbg5j/+nSbNf9
            kMt9YhSVPxKHMWWnnxzt7y4kgCnGc3NCzvWPwl17Mwkpnw1NO925Vv0r3NolIeLS
            XgHPh/o5dO/jw2aqgQ8EcT43X1C1q68K8YocvFQmJUV78GTdfZ8Noa8YN2QiOsFW
            rvfpAf+As9D4pZDb2+Vd4dVYqoTL1TmTq4pO8/0ZmkABzQWLE3BS5eNbzlEwsyI=
            =+dgW
            -----END PGP MESSAGE-----
          fp: 131E4591ED22C309ED38E3702A0FD38CA7C19B26
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
