# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4iyTjyYL8TZCRCT8fpE=,iv:yWUxL/RXBTwaMopNHgemsQV9351a0N24sqtm/I33Rio=,tag:wydSj89py9aYBlpu81tXqA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZLA+Hfr7YREwngs3wpAKcVp/,iv:1CJxqNoXY5LzmBxdbUlRK/bkJxlHGp86sSl7Ce4ZcD4=,tag:WL9WQiw6muhSbpDRNOqfPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-08T03:42:17Z"
    mac: ENC[AES256_GCM,data:RlIQPJJUX4lX+0ebr7Gvr1Avl8qRJP/CS4431X8hWjKgyZNgq6j06p51+4LkBXqa2GEsTQ2hToebitrAEJCi7eC+C2hT+ZgLotdIfcJZG0VC+MU5fG/JovNp3vMgEzN44neQpW09et3rEBT1Hj15nsd/L4w+8ubp2wa7um0ODfI=,iv:uxmc0Ud5mF0jfYiGgX1gHGXYBiNnRmHXCJAPERILRmc=,tag:MMqKCZWx0hb4F5jg7nOYOw==,type:str]
    pgp:
        - created_at: "2021-09-08T03:42:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4gzIuqEmpK/AQ//VVYVzyWvwBT/Xqq758tJ9vubfb1vkYg4pwAo4ZlIl7x5
            tgHATt2T2Og/EFLw4w+7Xm1zXTauNnMuEhPM3l5ATkt2/NnKEi4wTTHigTBn300E
            JQfzIyF2leXBgb+8tmncPEjU491CDHgIyL/3v4IIYduoI7h9scJjSC/z633PhzmO
            Q2Cfa7bXzIdO4D6YbIS61hoQu+OSXEnqcMVPJS4l8qZHGGUZNx9nYRSMTjKEQXO7
            VLJ58CYH7LJUXQkRjv7lJJ+KkQqY59iPw44BVeA6Dt88GLBC6dunccvVEM0am8uF
            DdNIE2LWoQmmDupu+3tnI4Atc/nCaN4CErgD+fzj2DeGs7CnbUkhlWSMe+FesV12
            w98W0WxTqVMigw3g0BI41yWcX+2T24m7FxQG56JJvj6d/eCwTTgIucThHBV3EOxs
            Xl4MgEcEsFHa9PMx/UdKEhwZ6/CyB/T65rXN1SeWhpR7232mVddqo8/ZD9jStcw8
            cEZ+u7snJs4lnHv8caQ2L1LZ23CGtDO9+m4fWlIJjIC/ad63Lo0xOY0EDL3RPkWc
            TmYv26RK9X7W/VkrEs4MwNBCD7dLQh46/hy9zEmKQB8WNjTld4niYBY/MmuA3sAg
            2iGu4ics14y3wVHphojsO4zhotAjoS2CPs5de6IB5LjIWAqYVi6dtlUHc1K/MDXS
            XAFdfZ7HuK7JNSP1SVUkjVsC/H5olekwCQToyBiSrNZYeBoEU9g6d5qfMyWdSjW5
            0wFxFUwYGVfhik7T8wwQjtxP3ObETzBu6kc5VTv6QK1Sfeuy11DxqSnGAh4s
            =8gy1
            -----END PGP MESSAGE-----
          fp: DEAD17F94A4CBA3331BD2542F2FB94B62CC9EE0E
        - created_at: "2021-09-08T03:42:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/3Zqf7p544gAQ/+PXaicwao/Ol09j2yb+nRGt2RWoDxzvnxn5AGExiOnFY4
            AobGsYRxszvScgZ3JscccUhx5Jkw3a6WvBECv7uhdyXy5Vevthl7RZZWSmECkqhp
            /lxWVXt92OIHC8YSuhq1R/ccBF3+h/oUiXnvkXQt0Zn4c4cgUqsZtI7J5W5LlI45
            WWH0u4gZ6lCHW67z7xtGMSt5C4hv+LkxOtkAtQDwtVVdLiMZ0VGj3T8rPck0se/l
            Ydt8f7YgvFRo+URtKWFhN4sNYx6ljcI4jPdfi42YJmyjTOijY40H9Ps/hXGS2LeF
            DVYfV30XR+qoRgIyCkHrO02x4DlJBJpe34QN6efvitg7mwC+vO3K2wrr5mIFNbp4
            p128gZf6uqVjUk7XQl+Z5DMXkRE6NRVk1D+56sl/W564tniqPrpmjFADdEuZ3NOG
            +XRrHBRwsEclVbqblhqF+EzYT9e39LXHORBu3Ek8gG17ebcD/IInKYvOMl6C2brT
            3r1KgRb9G0TXbaQIESfwvoTZHnhlYCD4P0intjl6xbBSiO25RdnCZuFih7+Qx525
            1eiyBn2s8GmyMkDXkAlQn65CeWAyRVTWkDiAidv2IsIw/gFZLhIlxvRyFVmdQxC5
            p0sBD2mscE7Rem48n190cIAcibf3tquCaHTXWIE6bmgYf1RA8Q55w1YuxYMDAFzS
            XAGlC1SOm27FbFrrK6LFjm03L44ihxNBS+zDGw0LGIw6BOq/y79Uk+YPUmqBZ/pX
            RsUmmD0zR30CIbEnN6rO5ZDynUMvpCSNm4Sr/U1kCuZAq9Hn6k1iVcqC5vyr
            =MKqS
            -----END PGP MESSAGE-----
          fp: 131E4591ED22C309ED38E3702A0FD38CA7C19B26
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
